version: "3"

services:
    postgres:
        image: postgres:13-alpine
        restart: unless-stopped
        container_name: travelly_pg
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-gak597229}
            - POSTGRES_USER=${POSTGRES_USER:-smart_duck}
            - POSTGRES_DB=${POSTGRES_DB:-travelly_db}
        volumes:
            - ./.docker/data/postgresql/:/var/lib/postgresql/data/
        ports:
            - 0.0.0.0:5000:5432

    nginx:
        image: nginx:alpine
        ports:
            - "80:80"
            - "5050:5050"
        volumes:
             - ./.docker/etc/nginx/:/etc/nginx/


    profile:
        build: ./services/user_service
        restart: unless-stopped
        container_name: travelly_api_profile
        depends_on:
            - postgres
        ports:
            - 0.0.0.0:5001:5001

    auth:
        build: ./services/auth_service
        restart: unless-stopped
        container_name: travelly_api_auth
        depends_on:
            - postgres
        ports:
            - 0.0.0.0:5002:5002

    feed:
        build: ./services/feed_service
        restart: unless-stopped
        container_name: travelly_api_feed
        depends_on:
            - postgres
        ports:
            - 0.0.0.0:5004:5004

    info:
        build: ./services/full_info_service
        restart: unless-stopped
        container_name: travelly_api_info
        depends_on:
            - postgres
        ports:
            - 0.0.0.0:5005:5005