version: "3"

services:
    postgres:
        image: postgres:13-alpine
        restart: unless-stopped
        container_name: travelly_pg
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-gak597229}
            - POSTGRES_USER=${POSTGRES_USER:-smart_duck}
            - POSTGRES_DB=${POSTGRES_DB:-travelly_db}
        volumes:
            - ./.docker/data/postgresql/:/var/lib/postgresql/data/
        ports:
            - "0.0.0.0:5000:5432"

    nginx:
        image: nginx:alpine
        ports:
            - "80:80"
            - "5050:5050"
        volumes:
             - ./.docker/etc/nginx/:/etc/nginx/


    backend_1:
        build: ./backend_1
        restart: unless-stopped
        container_name: backend_1
        depends_on:
            - postgres
        ports:
            - "5001:5001"

    backend_2:
        build: ./backend_2
        restart: unless-stopped
        container_name: backend_2
        depends_on:
            - postgres
        ports:
            - "5002:5002"

    backend_3:
        build: ./backend_3
        restart: unless-stopped
        container_name: backend_3
        depends_on:
            - postgres
        ports:
            - "5003:5003"